name: 수정 제안
description: 소프트웨어나 문서의 개선을 위한 제안을 해주세요.
title: "[SUGGESTION] "
labels: [enhancement, suggestion]
assignees: []
body:
  - type: markdown
    attributes:
      value: "이 수정 제안서를 작성해주셔서 감사합니다! 아래의 질문에 답해 주시면, 우리가 제안을 이해하고 고려할 수 있습니다."
  - type: input
    id: feature-summary
    attributes:
      label: 제안 요약
      description: 제안하고자 하는 기능을 한 문장으로 요약해 주세요.
      placeholder: 여기에 요약을 입력하세요.
    validations:
      required: true
  - type: textarea
    id: details
    attributes:
      label: 상세 제안 내용
      description: 제안의 배경과 구체적인 내용을 자세히 설명해 주세요.
      placeholder: "제안의 배경, 기능 구현 아이디어, 그리고 이 제안이 필요한 이유를 설명해 주세요."
    validations:
      required: true
  - type: textarea
    id: benefits
    attributes:
      label: 기대 효과
      description: 이 제안을 통해 기대하는 결과나 이점을 설명해 주세요.
      placeholder: "이 제안을 통해 기대하는 결과나 이점을 설명해 주세요."
    validations:
      required: false
